{{-- pages.X.blade.php --}}
@extends('layouts.main')

<style>

p {
    color: yellow;

}

</style>


@section('main')
<h1>Fonts in use in this project</h1>
<h2><code>.font-serif {font-family: $font-family-google-serif;}</code></h2>
<p class="font-serif">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>.font-sans-serif{font-family: $font-family-google-sans-serif;}</code></h2>
<p class="font-sans-serif">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>.font-monospace {$font-family-google-monospace;}</code></h2>
<p class="font-monospace">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>.font-display {$font-family-google-display;}</code></h2>
<p class="font-display">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>.font-hand-writing {$font-family-google-hand-writing }</code></h2>
<p class="font-hand-writing ">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>g-font-1</code></h2>
<p class="g-font-1">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>g-font-2</code></h2>
<p class="g-font-2">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>g-font-3</code></h2>
<p class="g-font-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>g-font-4</code></h2>
<p class="g-font-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>g-font-5</code></h2>
<p class="g-font-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>g-font-6</code></h2>
<p class="g-font-6">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>g-font-7</code></h2>
<p class="g-font-7">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>g-font-8</code></h2>
<p class="g-font-8">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>g-font-9</code></h2>
<p class="g-font-9">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>g-font-10</code></h2>
<p class="g-font-10">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
<h2><code>g-font-11</code></h2>
<p class="g-font-11">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore ducimus unde asperiores quae ad, doloribus nisi commodi! Quibusdam corporis facere ab perspiciatis id autem cupiditate voluptatum consectetur molestiae, nobis culpa ullam voluptates ad illo consequatur cum at dolore itaque provident dignissimos sit asperiores sint reiciendis harum. Amet maiores magni ratione tenetur quidem natus iste, incidunt similique qui quos molestiae in officiis assumenda sint quis, hic ullam aliquam, architecto rerum dolor. Natus cum nihil enim. Eaque vel ex aliquam dolorem iusto quae eos, deleniti, eveniet commodi at ipsa illo, veritatis neque consequatur assumenda tenetur ab atque saepe voluptates ullam nisi ut ad? Tenetur eum saepe culpa atque dolore, aut animi omnis architecto quia fuga consequuntur nostrum veniam unde rerum numquam, vitae, assumenda totam neque eius fugit suscipit debitis! Quae laboriosam explicabo, doloremque ut at, quos impedit minima autem deserunt magnam nulla, tenetur obcaecati amet vel consequuntur libero iusto! Ea, iusto hic.</p>
<hr>
@endsection
@section('scripts')
  @parent
@endsection
